{{- $g := fromJson (include "eric-enm-search-engine-rollback.global" .) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "eric-enm-search-engine-rollback.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations: {{- include "eric-enm-search-engine-rollback.annotations" . | nindent 4 }}
  labels: {{- include "eric-enm-search-engine-rollback.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels: {{- include "eric-enm-search-engine-rollback.labels" . | nindent 8 }}
      annotations: {{- include "eric-enm-search-engine-rollback.annotations" . | nindent 8 }}
    spec:
    {{- if .Values.podPriority }}
    {{- if .Values.podPriority.priorityClassName }}
      priorityClassName: {{ .Values.podPriority.priorityClassName | quote }}
    {{- end }}
    {{- end }}
      containers:
        - name: maincontainer
          image: {{ template "eric-enm-search-engine-rollback.mainImagePath" . }}
          imagePullPolicy: {{ template "eric-enm-search-engine-rollback.registryImagePullPolicy" . }}
          command: [ '/bin/sh', '-c', "echo 'hello' >>sample.txt"]
          resources:
            requests:
            {{- if .Values.resources.maincontainer.requests.cpu }}
              cpu: {{ .Values.resources.maincontainer.requests.cpu | quote }}
            {{- end }}
            {{- if .Values.resources.maincontainer.requests.memory }}
              memory: {{ .Values.resources.maincontainer.requests.memory | quote }}
            {{- end }}
            {{- if (index .Values "resources" "maincontainer" "requests" "ephemeral-storage") }}
            {{ println "  ephemeral-storage:" (index .Values "resources" "maincontainer" "requests" "ephemeral-storage" | quote) }}
            {{- end }}
            limits:
            {{- if .Values.resources.maincontainer.limits.cpu }}
              cpu: {{ .Values.resources.maincontainer.limits.cpu | quote }}
            {{- end }}
            {{- if .Values.resources.maincontainer.limits.memory }}
              memory: {{ .Values.resources.maincontainer.limits.memory | quote }}
            {{- end }}
            {{- if (index .Values "resources" "maincontainer" "limits" "ephemeral-storage") }}
            {{ println "  ephemeral-storage:" (index .Values "resources" "maincontainer" "limits" "ephemeral-storage" | quote) }}
            {{- end }}
          env:
          - name: STORAGE_CONNECTIVITY
            value: {{ .Values.persistentVolumeClaim.storageConnectivity | default "networked" | quote }}
          volumeMounts:
          - name: data
            mountPath: {{ .Values.persistentVolumeClaim.mountPath | quote }}
            subPath: {{ .Values.persistentVolumeClaim.subPath | quote }}
      volumes:
      - name: data
      {{- if .Values.persistentVolumeClaim.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaim.existingClaim | default (include "eric-enm-search-engine-rollback.name" .) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- if include "eric-enm-search-engine-rollback.pullSecrets" . }}
      imagePullSecrets:
        - name: {{ template "eric-enm-search-engine-rollback.pullSecrets" . }}
      {{- end }}
      {{- if (or .Values.nodeSelector $g.nodeSelector) }}
      nodeSelector: {{- include "eric-enm-search-engine-rollback.nodeSelector" . | nindent 8 }}
      {{- end }}
{{- if eq .Values.affinity.podAntiAffinity "hard" }}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ include "eric-enm-search-engine-rollback.name" . }}
            topologyKey: {{ .Values.affinity.topologyKey }}
{{- else if eq .Values.affinity.podAntiAffinity  "soft" }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ include "eric-enm-search-engine-rollback.name" . }}
              topologyKey: {{ .Values.affinity.topologyKey }}
{{- end }}
      restartPolicy: OnFailure
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}