apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-enm-search-engine-rollback.name" . }}
  labels: {{- include "eric-enm-search-engine-rollback.labels" . | nindent 4 }}
  annotations: {{- include "eric-enm-search-engine-rollback.annotations" . | nindent 4 }}
automountServiceAccountToken: true
